---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portworx-sc-gitlab
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-pvc
spec:
  storageClassName: portworx-sc-gitlab
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
        name: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/etc/gitlab"
          name: gitlab-volume
        - mountPath: "/var/log/gitlab"
          name: gitlab-volume
        - mountPath: "/var/opt/gitlab"
          name: gitlab-volume
      volumes:
      - name: gitlab-volume
        persistentVolumeClaim:
          claimName: gitlab-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
spec:
  selector:
    app: gitlab
  ports:
  - port: 80
    targetPort: 80
    name: gitlab-http
  - port: 443
    targetPort: 443
    name: gitlab-https
  - port: 22
    targetPort: 22
    name: gitlab-ssh
  externalTrafficPolicy: Local
  type: LoadBalancer
