---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portworx-sc-heimdall
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: heimdall-data-pvc
spec:
  storageClassName: portworx-sc-heimdall
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
        name: heimdall
    spec:
      containers:
      - name: heimdall
        image: linuxserver/heimdall
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/New_York"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: "/config"
          name: heimdall-data-volume
      volumes:
      - name: heimdall-data-volume
        persistentVolumeClaim:
          claimName: heimdall-data-pvc
      nodeSelector:
        portworx: "true"
---

apiVersion: v1
kind: Service
metadata:
  name: heimdall
spec:
  selector:
    app: heimdall
  ports:
  - port: 80
    targetPort: 80
    name: heimdall-http
    name: heimdall
  externalTrafficPolicy: Local
  type: LoadBalancer
