---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portworx-sc-unifi
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-pvc
spec:
  storageClassName: portworx-sc-unifi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  labels:
    app: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi
  template:
    metadata:
      labels:
        app: unifi
        name: unifi
    spec:
      containers:
      - name: unifi
        image: linuxserver/unifi-controller
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: MEM_LIMIT
          value: "1024M"
        volumeMounts:
        - mountPath: "/config"
          name: unifi-volume
      volumes:
      - name: unifi-volume
        persistentVolumeClaim:
          claimName: unifi-pvc
      nodeSelector:
        portworx: "true"
---

apiVersion: v1
kind: Service
metadata:
  name: unifi-tcp-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi
spec:
  selector:
    app: unifi
  ports:
  - port: 8080
    targetPort: 8080
    name: unifi-http
  - port: 8443
    targetPort: 8443
    name: unifi-https
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 10.0.10.162
---

apiVersion: v1
kind: Service
metadata:
  name: unifi-udp-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi
spec:
  selector:
    app: unifi
  ports:
  - port: 3478
    targetPort: 3478
    protocol: UDP
    name: unifi-discover-01
  - port: 10001
    targetPort: 10001
    protocol: UDP
    name: unifi-discover-02
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 10.0.10.162
